name: Repo Properties

on:
  workflow_dispatch:
    inputs:
      repo-name:
        type: string
        description: Repository Name
        required: true
      property-name: 
        type: string
        description: Property to Update
        required: true
      property-value:
        type: string
        description: Value
        required: true
      
env:
  GH_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN}}

jobs:
  set-properties:
    runs-on: ubuntu-latest
    steps:
      - name: Get properties
        run: |
          curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GH_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/orgs/${{github.repository_owner}}/properties/values \
          -d '{"repository_names":["${{ github.event.inputs.repo-name }}"],"properties":[{"property_name":"${{github.event.inputs.property-name}}","value":"${{ github.event.inputs.property-value}}"}]}'
